### ISSUE TITLE
Attempt to setup Open Collective notes

### ISSUE THREAD

**Issue by monkeywithacupcake** [browsh-org/www.brow.sh#1]
Hi, I'm helping set up repos for Open Collective. This repo does not have a README.md, so I could not add the Badges and Support sections. (It would look a little sparse with just those, so I also did not create it.)  

NOTE, also: your github link in the footer of the site goes to **https://github.com/https://github.com/browsh-org** - this could be fixed in `footer.html`, but I am not sure if you want to change the liquid tag or remove the additional https://github.com.

Cheers on the project.

**Comment by tombh** [comment]
Thanks, this project is still in private beta. And in fact the repo to which the Open Collective account is connected is the Texttop one I used to register. But I don't want to make the name change until everything is ready to go live. If you like you could use the README on this branch of Texttop repo https://github.com/tombh/texttop/tree/webext-rewrite I just don't know when it'll all be made public. Maybe a month or so.

**Comment by monkeywithacupcake** [comment]
Ok. We can wait until you are ready if you want. Just reach out to OpenCollective - slack is best if you have it (https://slack.opencollective.com/) when you are ready and identify the repo that you want to use. Cheers!

**Comment by tombh** [comment]
I've decided just to stick with Patreon/Paypal/Bitcoin for now. I'll revisit this later.
