### ISSUE TITLE
open graph icon

### ISSUE THREAD

**Issue by ghost** [browsh-org/www.brow.sh#10]
It is always nice to have an icon linked to open graph, so pages and programs crawling og can show it.
Maybe take the logo or the favicon and create an image which you can link with something like this:
```
<meta property="og:image" content="og_logo.png">
<meta property="og:image:width" content="512">
<meta property="og:image:height" content="512">
<meta property="og:image:type" content="image/png">
```

PS:  perhaps I could do this for you

**Comment by tombh** [comment]
Oh yes, please do add this!
