### ISSUE TITLE
performance improvements

### ISSUE THREAD

**Issue by BO41** [browsh-org/www.brow.sh#11]
I ran the [lighthouse](https://developers.google.com/web/tools/lighthouse/) test by chrome, and it has some suggestions to improve site performance:

```
Avoid multiple, costly round trips to any origin
Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. 
https://fonts.gstatic.com | 530 ms
https://s.ytimg.com | 470 ms
https://i.ytimg.com | 470 ms
https://srv.carbonads.net | 450 ms
https://www.google.com | 330 ms
https://googleads.g.doubleclick.net
```
[Learn more.](https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect)

```
Uses inefficient cache policy on static assets
15 assets found
A long cache lifetime can speed up repeat visits to your page. 
```
/carbon.js?serve=CKYIT23L&placement=wwwbrowsh(cdn.carbonads.com) | None | 12 KB
-- | -- | --
/ads/CKYIT23L.json?segment=…(srv.carbonads.net) | None | 1 KB
/instream/ad_status.js(static.doubleclick.net) | 15 m | 0 KB
…images/browsh-html.jpg(www.brow.sh) | 1 h | 69 KB
…images/browsh-tty.jpg(www.brow.sh) | 1 h | 66 KB
…js/main.min.js(www.brow.sh) | 1 h | 39 KB
…images/browsh-header.jpg(www.brow.sh) | 1 h | 15 KB
…css/main.css(www.brow.sh) | 1 h | 12 KB
…css/carbonads.css(www.brow.sh) | 1 h | 1 KB
…zqAoBD62gvo/maxresdefault.jpg(i.ytimg.com) | 2 h | 199 KB
/static/seedanddew_v1.min.js(www.seedanddew.com) | 4 h | 0 KB
/static/embed.min.js(www.seedanddew.com) | 4 h | 0 KB
…en_GB/base.js(www.youtube.com) | 8 d | 431 KB
…en_GB/base.js(www.youtube.com) | 8 d | 95 KB
…www-embed…/www-embed-player.js(www.youtube.com) | 8 d | 37 KB

[Learn more.](https://developers.google.com/web/tools/lighthouse/audits/cache-policy)

**Comment by tombh** [comment]
I actually really want to make a serious improvement to the site's performance. Seeing as Browsh is actually aimed at people with slow internet, then those people need to be able to easily view the main Browsh website!

So the biggest issues are the video, the ads and the fonts. The fonts can definitely just go, falling back to local fonts is fine. Perhaps the video could dynamically embed itself on mouse over? As for the ads, well they're one of main hopes for being able to make Browsh my job, so I'm just going to hope that users on slow internet know enough to block ads.

**Comment by BO41** [comment]
@tombh the performance is really not bad.

But those things I listed can easily be fixed, at least some of it.

 1. Increase cache time via the server or with a `.htaccess` (could create a PR for this case).
Then at least your resources are handled better.
2. "adding preconnect or dns-prefetch resource hints" is also easy to do
- https://www.viget.com/articles/make-your-site-faster-with-preconnect-hints/
- https://www.machmetrics.com/speed-blog/guide-to-browser-hints-preload-preconnect-prefetch/
- https://www.cdnplanet.com/blog/faster-google-webfonts-preconnect/

the other changes you proposed take more effort and time, but of course would also help :+1:
