### ISSUE TITLE
best practices

### ISSUE THREAD

**Issue by BO41** [browsh-org/www.brow.sh#12]
`<frame> or <iframe> elements do not have a title`
>Failing Elements:
><iframe src="https://www.youtube.com/embed/zqAoBD62gvo" frameborder="0" allow="autoplay;encrypted-media" allowfullscreen="" id="fitvid0"></iframe>

---

missing page description on:
https://www.brow.sh/docs/installation/

---
use a unique description:
- www.brow.sh
- www.brow.sh/donate
- www.brow.sh/download

all have the same

**Comment by BO41** [comment]
I can fix some of the points :)
just say what you think about it and if it is needed

**Comment by tombh** [comment]
Totally agree about adding `_blank` to external links!

**Comment by BO41** [comment]
Update:
only page descriptions are missing.
one completely, others are not unique
