### ISSUE TITLE
keyboard only (mouseless) browsing 

### ISSUE THREAD

**Issue by wokawoka** [browsh-org/www.brow.sh#23]
Fantastic project!
Do you think that it will be eventually possible to implement in the future a way to browse without a mouse ? 
I'm trying to browse via ssh from a the device that unfortunately doesn't have a touchscreen nor a mouse.
It would be incredibly cool if it would be possible to browse through keystrokes in the same way that it was possible with links.
From my point of view that's the only thing that I find that is missing, otherwise brow.sh is the coolest thing I've stepped into since a long time. Thank you so much from what you have done.

**Comment by wokawoka** [comment]
Maybe these firefox addons/resources could be useful for the purpose? :
https://addons.mozilla.org/en-US/firefox/addon/vimfx/
https://addons.mozilla.org/en-US/firefox/addon/mouseless-plugin/
https://addons.mozilla.org/de/firefox/addon/td-mouseless-browsing/
https://bugzilla.mozilla.org/show_bug.cgi?id=1215061

I guess that I would not be the only one who would benefit from a mouseless/linkslike way of browsing from brow.sh. What do you think?

**Comment by BO41** [comment]
@wokawoka I think you are in the wrong project.
this is the repo for www.brow.sh.
The repo for the brow.sh browser is [here](https://github.com/browsh-org/browsh).

There are already some similar issues to this: https://github.com/browsh-org/browsh/issues/85, https://github.com/browsh-org/browsh/issues/52, https://github.com/browsh-org/browsh/issues/31

**Comment by wokawoka** [comment]
Ouch, sorry for that and thank you for redirecting me to the right repo.
