### ISSUE TITLE
`brow.sh` does not redirect to `www.brow.sh`

### ISSUE THREAD

**Issue by 0xCMP** [browsh-org/www.brow.sh#26]
Screenshot of `https://brow.sh`

![image](https://user-images.githubusercontent.com/505649/80612770-6e1e3180-8a0a-11ea-937c-504c277ac3f6.png)

Seems like it needs an automatic redirect to `https://www.brow.sh` which works fine.

**Comment by tombh** [comment]
Thanks a lot for reporting this. I think I've fixed it. Does it work now?

**Comment by 0xCMP** [comment]
Yes, looks like it's working now

**Comment by tombh** [comment]
Thanks
