### ISSUE TITLE
html errors

### ISSUE THREAD

**Issue by BO41** [browsh-org/www.brow.sh#8]
on brows.sh there are some HTML errors.
some don't matter, but others could/should be fixed

```
An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.

Attribute “count” not allowed on element “button” at this point.

Element “div” not allowed as child of element “button” in this context. (Suppressing further errors from this subtree.)

An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.

An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.

Attribute “allow” not allowed on element “iframe” at this point.

The “frameborder” attribute on the “iframe” element is obsolete. Use CSS instead.

An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.

The “itemprop” attribute was specified, but the element is not a property of any item.
```

**Comment by tombh** [comment]
Which ones do you think we should fix?

**Comment by BO41** [comment]
@tombh 
- I think all images should have an `alt` tag.
- having "invalid" attributes is not recommended, but in some cases needed or useful, so if it has an purpose, leave it.
- having a `div` as child of `button` should be fixable. Either the div is not needed, or you could remove the button and give the div an onclick
- >Attribute “allow” not allowed on element “iframe” at this point.

should be fixable too, but I don't know where this is the case
- >The “frameborder” attribute on the “iframe” element is obsolete. Use CSS instead.

speaks for itself
- I never heard of the `itemprop` attribute, so I can't say anything about it

**Comment by BO41** [comment]
I can fix some of the errors myself :)
